/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GETAccountAccountIdRatedTvEpisodes200ResponseResultsInner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GETAccountAccountIdRatedTvEpisodes200Response
 */
public class GETAccountAccountIdRatedTvEpisodes200ResponseTest {
    private final GETAccountAccountIdRatedTvEpisodes200Response model = new GETAccountAccountIdRatedTvEpisodes200Response();

    /**
     * Model tests for GETAccountAccountIdRatedTvEpisodes200Response
     */
    @Test
    public void testGETAccountAccountIdRatedTvEpisodes200Response() {
        // TODO: test GETAccountAccountIdRatedTvEpisodes200Response
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'results'
     */
    @Test
    public void resultsTest() {
        // TODO: test results
    }

    /**
     * Test the property 'totalPages'
     */
    @Test
    public void totalPagesTest() {
        // TODO: test totalPages
    }

    /**
     * Test the property 'totalResults'
     */
    @Test
    public void totalResultsTest() {
        // TODO: test totalResults
    }

}
