/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GETGuestSessionGuestSessionIdRatedTvEpisodes200ResponseResultsInner
 */
public class GETGuestSessionGuestSessionIdRatedTvEpisodes200ResponseResultsInnerTest {
    private final GETGuestSessionGuestSessionIdRatedTvEpisodes200ResponseResultsInner model = new GETGuestSessionGuestSessionIdRatedTvEpisodes200ResponseResultsInner();

    /**
     * Model tests for GETGuestSessionGuestSessionIdRatedTvEpisodes200ResponseResultsInner
     */
    @Test
    public void testGETGuestSessionGuestSessionIdRatedTvEpisodes200ResponseResultsInner() {
        // TODO: test GETGuestSessionGuestSessionIdRatedTvEpisodes200ResponseResultsInner
    }

    /**
     * Test the property 'airDate'
     */
    @Test
    public void airDateTest() {
        // TODO: test airDate
    }

    /**
     * Test the property 'episodeNumber'
     */
    @Test
    public void episodeNumberTest() {
        // TODO: test episodeNumber
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'overview'
     */
    @Test
    public void overviewTest() {
        // TODO: test overview
    }

    /**
     * Test the property 'seasonNumber'
     */
    @Test
    public void seasonNumberTest() {
        // TODO: test seasonNumber
    }

    /**
     * Test the property 'showId'
     */
    @Test
    public void showIdTest() {
        // TODO: test showId
    }

    /**
     * Test the property 'stillPath'
     */
    @Test
    public void stillPathTest() {
        // TODO: test stillPath
    }

    /**
     * Test the property 'voteCount'
     */
    @Test
    public void voteCountTest() {
        // TODO: test voteCount
    }

}
