/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GETMovieMovieIdCredits200ResponseCastInner
 */
public class GETMovieMovieIdCredits200ResponseCastInnerTest {
    private final GETMovieMovieIdCredits200ResponseCastInner model = new GETMovieMovieIdCredits200ResponseCastInner();

    /**
     * Model tests for GETMovieMovieIdCredits200ResponseCastInner
     */
    @Test
    public void testGETMovieMovieIdCredits200ResponseCastInner() {
        // TODO: test GETMovieMovieIdCredits200ResponseCastInner
    }

    /**
     * Test the property 'adult'
     */
    @Test
    public void adultTest() {
        // TODO: test adult
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'knownForDepartment'
     */
    @Test
    public void knownForDepartmentTest() {
        // TODO: test knownForDepartment
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'originalName'
     */
    @Test
    public void originalNameTest() {
        // TODO: test originalName
    }

    /**
     * Test the property 'popularity'
     */
    @Test
    public void popularityTest() {
        // TODO: test popularity
    }

    /**
     * Test the property 'profilePath'
     */
    @Test
    public void profilePathTest() {
        // TODO: test profilePath
    }

    /**
     * Test the property 'castId'
     */
    @Test
    public void castIdTest() {
        // TODO: test castId
    }

    /**
     * Test the property 'character'
     */
    @Test
    public void characterTest() {
        // TODO: test character
    }

    /**
     * Test the property 'creditId'
     */
    @Test
    public void creditIdTest() {
        // TODO: test creditId
    }

    /**
     * Test the property 'order'
     */
    @Test
    public void orderTest() {
        // TODO: test order
    }

}
