/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GETMovieMovieIdAlternativeTitles200ResponseTitlesInner
 */
public class GETMovieMovieIdAlternativeTitles200ResponseTitlesInnerTest {
    private final GETMovieMovieIdAlternativeTitles200ResponseTitlesInner model = new GETMovieMovieIdAlternativeTitles200ResponseTitlesInner();

    /**
     * Model tests for GETMovieMovieIdAlternativeTitles200ResponseTitlesInner
     */
    @Test
    public void testGETMovieMovieIdAlternativeTitles200ResponseTitlesInner() {
        // TODO: test GETMovieMovieIdAlternativeTitles200ResponseTitlesInner
    }

    /**
     * Test the property 'iso31661'
     */
    @Test
    public void iso31661Test() {
        // TODO: test iso31661
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
