/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.GETMovieMovieIdTranslations200ResponseTranslationsInnerData;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GETMovieMovieIdTranslations200ResponseTranslationsInner
 */
public class GETMovieMovieIdTranslations200ResponseTranslationsInnerTest {
    private final GETMovieMovieIdTranslations200ResponseTranslationsInner model = new GETMovieMovieIdTranslations200ResponseTranslationsInner();

    /**
     * Model tests for GETMovieMovieIdTranslations200ResponseTranslationsInner
     */
    @Test
    public void testGETMovieMovieIdTranslations200ResponseTranslationsInner() {
        // TODO: test GETMovieMovieIdTranslations200ResponseTranslationsInner
    }

    /**
     * Test the property 'iso31661'
     */
    @Test
    public void iso31661Test() {
        // TODO: test iso31661
    }

    /**
     * Test the property 'iso6391'
     */
    @Test
    public void iso6391Test() {
        // TODO: test iso6391
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'englishName'
     */
    @Test
    public void englishNameTest() {
        // TODO: test englishName
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
