/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GETPersonPersonIdTvCredits200ResponseCastInner
 */
public class GETPersonPersonIdTvCredits200ResponseCastInnerTest {
    private final GETPersonPersonIdTvCredits200ResponseCastInner model = new GETPersonPersonIdTvCredits200ResponseCastInner();

    /**
     * Model tests for GETPersonPersonIdTvCredits200ResponseCastInner
     */
    @Test
    public void testGETPersonPersonIdTvCredits200ResponseCastInner() {
        // TODO: test GETPersonPersonIdTvCredits200ResponseCastInner
    }

    /**
     * Test the property 'creditId'
     */
    @Test
    public void creditIdTest() {
        // TODO: test creditId
    }

    /**
     * Test the property 'originalName'
     */
    @Test
    public void originalNameTest() {
        // TODO: test originalName
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'genreIds'
     */
    @Test
    public void genreIdsTest() {
        // TODO: test genreIds
    }

    /**
     * Test the property 'character'
     */
    @Test
    public void characterTest() {
        // TODO: test character
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'posterPath'
     */
    @Test
    public void posterPathTest() {
        // TODO: test posterPath
    }

    /**
     * Test the property 'voteCount'
     */
    @Test
    public void voteCountTest() {
        // TODO: test voteCount
    }

    /**
     * Test the property 'voteAverage'
     */
    @Test
    public void voteAverageTest() {
        // TODO: test voteAverage
    }

    /**
     * Test the property 'popularity'
     */
    @Test
    public void popularityTest() {
        // TODO: test popularity
    }

    /**
     * Test the property 'episodeCount'
     */
    @Test
    public void episodeCountTest() {
        // TODO: test episodeCount
    }

    /**
     * Test the property 'originalLanguage'
     */
    @Test
    public void originalLanguageTest() {
        // TODO: test originalLanguage
    }

    /**
     * Test the property 'firstAirDate'
     */
    @Test
    public void firstAirDateTest() {
        // TODO: test firstAirDate
    }

    /**
     * Test the property 'backdropPath'
     */
    @Test
    public void backdropPathTest() {
        // TODO: test backdropPath
    }

    /**
     * Test the property 'overview'
     */
    @Test
    public void overviewTest() {
        // TODO: test overview
    }

    /**
     * Test the property 'originCountry'
     */
    @Test
    public void originCountryTest() {
        // TODO: test originCountry
    }

}
