/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GETPersonPersonIdTvCredits200ResponseCastInner;
import org.openapitools.client.model.GETPersonPersonIdTvCredits200ResponseCrewInner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GETPersonPersonIdTvCredits200Response
 */
public class GETPersonPersonIdTvCredits200ResponseTest {
    private final GETPersonPersonIdTvCredits200Response model = new GETPersonPersonIdTvCredits200Response();

    /**
     * Model tests for GETPersonPersonIdTvCredits200Response
     */
    @Test
    public void testGETPersonPersonIdTvCredits200Response() {
        // TODO: test GETPersonPersonIdTvCredits200Response
    }

    /**
     * Test the property 'cast'
     */
    @Test
    public void castTest() {
        // TODO: test cast
    }

    /**
     * Test the property 'crew'
     */
    @Test
    public void crewTest() {
        // TODO: test crew
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
