/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GETPersonPersonId200Response
 */
public class GETPersonPersonId200ResponseTest {
    private final GETPersonPersonId200Response model = new GETPersonPersonId200Response();

    /**
     * Model tests for GETPersonPersonId200Response
     */
    @Test
    public void testGETPersonPersonId200Response() {
        // TODO: test GETPersonPersonId200Response
    }

    /**
     * Test the property 'knownForDepartment'
     */
    @Test
    public void knownForDepartmentTest() {
        // TODO: test knownForDepartment
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'alsoKnownAs'
     */
    @Test
    public void alsoKnownAsTest() {
        // TODO: test alsoKnownAs
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'biography'
     */
    @Test
    public void biographyTest() {
        // TODO: test biography
    }

    /**
     * Test the property 'popularity'
     */
    @Test
    public void popularityTest() {
        // TODO: test popularity
    }

    /**
     * Test the property 'profilePath'
     */
    @Test
    public void profilePathTest() {
        // TODO: test profilePath
    }

    /**
     * Test the property 'adult'
     */
    @Test
    public void adultTest() {
        // TODO: test adult
    }

    /**
     * Test the property 'imdbId'
     */
    @Test
    public void imdbIdTest() {
        // TODO: test imdbId
    }

}
