/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GETSearchPerson200ResponseResultsInner
 */
public class GETSearchPerson200ResponseResultsInnerTest {
    private final GETSearchPerson200ResponseResultsInner model = new GETSearchPerson200ResponseResultsInner();

    /**
     * Model tests for GETSearchPerson200ResponseResultsInner
     */
    @Test
    public void testGETSearchPerson200ResponseResultsInner() {
        // TODO: test GETSearchPerson200ResponseResultsInner
    }

    /**
     * Test the property 'profilePath'
     */
    @Test
    public void profilePathTest() {
        // TODO: test profilePath
    }

    /**
     * Test the property 'adult'
     */
    @Test
    public void adultTest() {
        // TODO: test adult
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'knownFor'
     */
    @Test
    public void knownForTest() {
        // TODO: test knownFor
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'popularity'
     */
    @Test
    public void popularityTest() {
        // TODO: test popularity
    }

}
