/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GETTvTvIdContentRatings200ResponseResultsInner
 */
public class GETTvTvIdContentRatings200ResponseResultsInnerTest {
    private final GETTvTvIdContentRatings200ResponseResultsInner model = new GETTvTvIdContentRatings200ResponseResultsInner();

    /**
     * Model tests for GETTvTvIdContentRatings200ResponseResultsInner
     */
    @Test
    public void testGETTvTvIdContentRatings200ResponseResultsInner() {
        // TODO: test GETTvTvIdContentRatings200ResponseResultsInner
    }

    /**
     * Test the property 'iso31661'
     */
    @Test
    public void iso31661Test() {
        // TODO: test iso31661
    }

    /**
     * Test the property 'rating'
     */
    @Test
    public void ratingTest() {
        // TODO: test rating
    }

}
