/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseCrewInner;
import org.openapitools.client.model.GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200Response
 */
public class GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseTest {
    private final GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200Response model = new GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200Response();

    /**
     * Model tests for GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200Response
     */
    @Test
    public void testGETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200Response() {
        // TODO: test GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200Response
    }

    /**
     * Test the property 'airDate'
     */
    @Test
    public void airDateTest() {
        // TODO: test airDate
    }

    /**
     * Test the property 'crew'
     */
    @Test
    public void crewTest() {
        // TODO: test crew
    }

    /**
     * Test the property 'episodeNumber'
     */
    @Test
    public void episodeNumberTest() {
        // TODO: test episodeNumber
    }

    /**
     * Test the property 'guestStars'
     */
    @Test
    public void guestStarsTest() {
        // TODO: test guestStars
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'overview'
     */
    @Test
    public void overviewTest() {
        // TODO: test overview
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'seasonNumber'
     */
    @Test
    public void seasonNumberTest() {
        // TODO: test seasonNumber
    }

    /**
     * Test the property 'stillPath'
     */
    @Test
    public void stillPathTest() {
        // TODO: test stillPath
    }

    /**
     * Test the property 'voteAverage'
     */
    @Test
    public void voteAverageTest() {
        // TODO: test voteAverage
    }

    /**
     * Test the property 'voteCount'
     */
    @Test
    public void voteCountTest() {
        // TODO: test voteCount
    }

}
