/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GETTvTvIdWatchProviders200ResponseResultsARFlatrateInner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GETTvTvIdWatchProviders200ResponseResultsRU
 */
public class GETTvTvIdWatchProviders200ResponseResultsRUTest {
    private final GETTvTvIdWatchProviders200ResponseResultsRU model = new GETTvTvIdWatchProviders200ResponseResultsRU();

    /**
     * Model tests for GETTvTvIdWatchProviders200ResponseResultsRU
     */
    @Test
    public void testGETTvTvIdWatchProviders200ResponseResultsRU() {
        // TODO: test GETTvTvIdWatchProviders200ResponseResultsRU
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'flatrate'
     */
    @Test
    public void flatrateTest() {
        // TODO: test flatrate
    }

    /**
     * Test the property 'free'
     */
    @Test
    public void freeTest() {
        // TODO: test free
    }

}
