/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GETTvTvId200ResponseNetworksInner
 */
public class GETTvTvId200ResponseNetworksInnerTest {
    private final GETTvTvId200ResponseNetworksInner model = new GETTvTvId200ResponseNetworksInner();

    /**
     * Model tests for GETTvTvId200ResponseNetworksInner
     */
    @Test
    public void testGETTvTvId200ResponseNetworksInner() {
        // TODO: test GETTvTvId200ResponseNetworksInner
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'logoPath'
     */
    @Test
    public void logoPathTest() {
        // TODO: test logoPath
    }

    /**
     * Test the property 'originCountry'
     */
    @Test
    public void originCountryTest() {
        // TODO: test originCountry
    }

}
