/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MovieListResultWithRatingObject
 */
public class MovieListResultWithRatingObjectTest {
    private final MovieListResultWithRatingObject model = new MovieListResultWithRatingObject();

    /**
     * Model tests for MovieListResultWithRatingObject
     */
    @Test
    public void testMovieListResultWithRatingObject() {
        // TODO: test MovieListResultWithRatingObject
    }

    /**
     * Test the property 'adult'
     */
    @Test
    public void adultTest() {
        // TODO: test adult
    }

    /**
     * Test the property 'backdropPath'
     */
    @Test
    public void backdropPathTest() {
        // TODO: test backdropPath
    }

    /**
     * Test the property 'genreIds'
     */
    @Test
    public void genreIdsTest() {
        // TODO: test genreIds
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'originalLanguage'
     */
    @Test
    public void originalLanguageTest() {
        // TODO: test originalLanguage
    }

    /**
     * Test the property 'originalTitle'
     */
    @Test
    public void originalTitleTest() {
        // TODO: test originalTitle
    }

    /**
     * Test the property 'overview'
     */
    @Test
    public void overviewTest() {
        // TODO: test overview
    }

    /**
     * Test the property 'releaseDate'
     */
    @Test
    public void releaseDateTest() {
        // TODO: test releaseDate
    }

    /**
     * Test the property 'posterPath'
     */
    @Test
    public void posterPathTest() {
        // TODO: test posterPath
    }

    /**
     * Test the property 'popularity'
     */
    @Test
    public void popularityTest() {
        // TODO: test popularity
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'video'
     */
    @Test
    public void videoTest() {
        // TODO: test video
    }

    /**
     * Test the property 'voteAverage'
     */
    @Test
    public void voteAverageTest() {
        // TODO: test voteAverage
    }

    /**
     * Test the property 'voteCount'
     */
    @Test
    public void voteCountTest() {
        // TODO: test voteCount
    }

    /**
     * Test the property 'rating'
     */
    @Test
    public void ratingTest() {
        // TODO: test rating
    }

}
