/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for POSTAccountAccountIdFavoriteRequest
 */
public class POSTAccountAccountIdFavoriteRequestTest {
    private final POSTAccountAccountIdFavoriteRequest model = new POSTAccountAccountIdFavoriteRequest();

    /**
     * Model tests for POSTAccountAccountIdFavoriteRequest
     */
    @Test
    public void testPOSTAccountAccountIdFavoriteRequest() {
        // TODO: test POSTAccountAccountIdFavoriteRequest
    }

    /**
     * Test the property 'mediaType'
     */
    @Test
    public void mediaTypeTest() {
        // TODO: test mediaType
    }

    /**
     * Test the property 'mediaId'
     */
    @Test
    public void mediaIdTest() {
        // TODO: test mediaId
    }

    /**
     * Test the property 'favorite'
     */
    @Test
    public void favoriteTest() {
        // TODO: test favorite
    }

}
