/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GETAuthenticationGuestSessionNew200Response
 */
@JsonPropertyOrder({
  GETAuthenticationGuestSessionNew200Response.JSON_PROPERTY_SUCCESS,
  GETAuthenticationGuestSessionNew200Response.JSON_PROPERTY_GUEST_SESSION_ID,
  GETAuthenticationGuestSessionNew200Response.JSON_PROPERTY_EXPIRES_AT
})
@JsonTypeName("GET_authentication_guest_session_new_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T11:26:21.377642+02:00[Europe/Paris]")
public class GETAuthenticationGuestSessionNew200Response {
  public static final String JSON_PROPERTY_SUCCESS = "success";
  private Boolean success;

  public static final String JSON_PROPERTY_GUEST_SESSION_ID = "guest_session_id";
  private String guestSessionId;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expires_at";
  private String expiresAt;

  public GETAuthenticationGuestSessionNew200Response() {
  }

  public GETAuthenticationGuestSessionNew200Response success(Boolean success) {
    
    this.success = success;
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSuccess() {
    return success;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccess(Boolean success) {
    this.success = success;
  }


  public GETAuthenticationGuestSessionNew200Response guestSessionId(String guestSessionId) {
    
    this.guestSessionId = guestSessionId;
    return this;
  }

   /**
   * Get guestSessionId
   * @return guestSessionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GUEST_SESSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGuestSessionId() {
    return guestSessionId;
  }


  @JsonProperty(JSON_PROPERTY_GUEST_SESSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGuestSessionId(String guestSessionId) {
    this.guestSessionId = guestSessionId;
  }


  public GETAuthenticationGuestSessionNew200Response expiresAt(String expiresAt) {
    
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * Get expiresAt
   * @return expiresAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresAt(String expiresAt) {
    this.expiresAt = expiresAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETAuthenticationGuestSessionNew200Response geTAuthenticationGuestSessionNew200Response = (GETAuthenticationGuestSessionNew200Response) o;
    return Objects.equals(this.success, geTAuthenticationGuestSessionNew200Response.success) &&
        Objects.equals(this.guestSessionId, geTAuthenticationGuestSessionNew200Response.guestSessionId) &&
        Objects.equals(this.expiresAt, geTAuthenticationGuestSessionNew200Response.expiresAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, guestSessionId, expiresAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETAuthenticationGuestSessionNew200Response {\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    guestSessionId: ").append(toIndentedString(guestSessionId)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

