/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GETCreditCreditId200ResponseMediaSeasonsInner
 */
@JsonPropertyOrder({
  GETCreditCreditId200ResponseMediaSeasonsInner.JSON_PROPERTY_AIR_DATE,
  GETCreditCreditId200ResponseMediaSeasonsInner.JSON_PROPERTY_POSTER_PATH,
  GETCreditCreditId200ResponseMediaSeasonsInner.JSON_PROPERTY_SEASON_NUMBER
})
@JsonTypeName("GET_credit_credit_id_200_response_media_seasons_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T11:26:21.377642+02:00[Europe/Paris]")
public class GETCreditCreditId200ResponseMediaSeasonsInner {
  public static final String JSON_PROPERTY_AIR_DATE = "air_date";
  private String airDate;

  public static final String JSON_PROPERTY_POSTER_PATH = "poster_path";
  private String posterPath;

  public static final String JSON_PROPERTY_SEASON_NUMBER = "season_number";
  private Integer seasonNumber;

  public GETCreditCreditId200ResponseMediaSeasonsInner() {
  }

  public GETCreditCreditId200ResponseMediaSeasonsInner airDate(String airDate) {
    
    this.airDate = airDate;
    return this;
  }

   /**
   * Get airDate
   * @return airDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AIR_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAirDate() {
    return airDate;
  }


  @JsonProperty(JSON_PROPERTY_AIR_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAirDate(String airDate) {
    this.airDate = airDate;
  }


  public GETCreditCreditId200ResponseMediaSeasonsInner posterPath(String posterPath) {
    
    this.posterPath = posterPath;
    return this;
  }

   /**
   * Get posterPath
   * @return posterPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POSTER_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPosterPath() {
    return posterPath;
  }


  @JsonProperty(JSON_PROPERTY_POSTER_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPosterPath(String posterPath) {
    this.posterPath = posterPath;
  }


  public GETCreditCreditId200ResponseMediaSeasonsInner seasonNumber(Integer seasonNumber) {
    
    this.seasonNumber = seasonNumber;
    return this;
  }

   /**
   * Get seasonNumber
   * @return seasonNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SEASON_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeasonNumber() {
    return seasonNumber;
  }


  @JsonProperty(JSON_PROPERTY_SEASON_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeasonNumber(Integer seasonNumber) {
    this.seasonNumber = seasonNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETCreditCreditId200ResponseMediaSeasonsInner geTCreditCreditId200ResponseMediaSeasonsInner = (GETCreditCreditId200ResponseMediaSeasonsInner) o;
    return Objects.equals(this.airDate, geTCreditCreditId200ResponseMediaSeasonsInner.airDate) &&
        Objects.equals(this.posterPath, geTCreditCreditId200ResponseMediaSeasonsInner.posterPath) &&
        Objects.equals(this.seasonNumber, geTCreditCreditId200ResponseMediaSeasonsInner.seasonNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(airDate, posterPath, seasonNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETCreditCreditId200ResponseMediaSeasonsInner {\n");
    sb.append("    airDate: ").append(toIndentedString(airDate)).append("\n");
    sb.append("    posterPath: ").append(toIndentedString(posterPath)).append("\n");
    sb.append("    seasonNumber: ").append(toIndentedString(seasonNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

