/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GETMovieMovieIdImages200ResponseBackdropsInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GETMovieMovieIdImages200Response
 */
@JsonPropertyOrder({
  GETMovieMovieIdImages200Response.JSON_PROPERTY_ID,
  GETMovieMovieIdImages200Response.JSON_PROPERTY_BACKDROPS,
  GETMovieMovieIdImages200Response.JSON_PROPERTY_POSTERS
})
@JsonTypeName("GET_movie_movie_id_images_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T11:26:21.377642+02:00[Europe/Paris]")
public class GETMovieMovieIdImages200Response {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_BACKDROPS = "backdrops";
  private List<GETMovieMovieIdImages200ResponseBackdropsInner> backdrops = null;

  public static final String JSON_PROPERTY_POSTERS = "posters";
  private List<GETMovieMovieIdImages200ResponseBackdropsInner> posters = null;

  public GETMovieMovieIdImages200Response() {
  }

  public GETMovieMovieIdImages200Response id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public GETMovieMovieIdImages200Response backdrops(List<GETMovieMovieIdImages200ResponseBackdropsInner> backdrops) {
    
    this.backdrops = backdrops;
    return this;
  }

  public GETMovieMovieIdImages200Response addBackdropsItem(GETMovieMovieIdImages200ResponseBackdropsInner backdropsItem) {
    if (this.backdrops == null) {
      this.backdrops = new ArrayList<>();
    }
    this.backdrops.add(backdropsItem);
    return this;
  }

   /**
   * Get backdrops
   * @return backdrops
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BACKDROPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GETMovieMovieIdImages200ResponseBackdropsInner> getBackdrops() {
    return backdrops;
  }


  @JsonProperty(JSON_PROPERTY_BACKDROPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBackdrops(List<GETMovieMovieIdImages200ResponseBackdropsInner> backdrops) {
    this.backdrops = backdrops;
  }


  public GETMovieMovieIdImages200Response posters(List<GETMovieMovieIdImages200ResponseBackdropsInner> posters) {
    
    this.posters = posters;
    return this;
  }

  public GETMovieMovieIdImages200Response addPostersItem(GETMovieMovieIdImages200ResponseBackdropsInner postersItem) {
    if (this.posters == null) {
      this.posters = new ArrayList<>();
    }
    this.posters.add(postersItem);
    return this;
  }

   /**
   * Get posters
   * @return posters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POSTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GETMovieMovieIdImages200ResponseBackdropsInner> getPosters() {
    return posters;
  }


  @JsonProperty(JSON_PROPERTY_POSTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPosters(List<GETMovieMovieIdImages200ResponseBackdropsInner> posters) {
    this.posters = posters;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETMovieMovieIdImages200Response geTMovieMovieIdImages200Response = (GETMovieMovieIdImages200Response) o;
    return Objects.equals(this.id, geTMovieMovieIdImages200Response.id) &&
        Objects.equals(this.backdrops, geTMovieMovieIdImages200Response.backdrops) &&
        Objects.equals(this.posters, geTMovieMovieIdImages200Response.posters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, backdrops, posters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETMovieMovieIdImages200Response {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    backdrops: ").append(toIndentedString(backdrops)).append("\n");
    sb.append("    posters: ").append(toIndentedString(posters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

