/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GETMovieMovieIdReviews200ResponseResultsInnerAuthorDetails
 */
@JsonPropertyOrder({
  GETMovieMovieIdReviews200ResponseResultsInnerAuthorDetails.JSON_PROPERTY_NAME,
  GETMovieMovieIdReviews200ResponseResultsInnerAuthorDetails.JSON_PROPERTY_USERNAME,
  GETMovieMovieIdReviews200ResponseResultsInnerAuthorDetails.JSON_PROPERTY_AVATAR_PATH
})
@JsonTypeName("GET_movie_movie_id_reviews_200_response_results_inner_author_details")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T11:26:21.377642+02:00[Europe/Paris]")
public class GETMovieMovieIdReviews200ResponseResultsInnerAuthorDetails {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_USERNAME = "username";
  private String username;

  public static final String JSON_PROPERTY_AVATAR_PATH = "avatar_path";
  private Object avatarPath;

  public GETMovieMovieIdReviews200ResponseResultsInnerAuthorDetails() {
  }

  public GETMovieMovieIdReviews200ResponseResultsInnerAuthorDetails name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public GETMovieMovieIdReviews200ResponseResultsInnerAuthorDetails username(String username) {
    
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsername(String username) {
    this.username = username;
  }


  public GETMovieMovieIdReviews200ResponseResultsInnerAuthorDetails avatarPath(Object avatarPath) {
    
    this.avatarPath = avatarPath;
    return this;
  }

   /**
   * Get avatarPath
   * @return avatarPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AVATAR_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getAvatarPath() {
    return avatarPath;
  }


  @JsonProperty(JSON_PROPERTY_AVATAR_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvatarPath(Object avatarPath) {
    this.avatarPath = avatarPath;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETMovieMovieIdReviews200ResponseResultsInnerAuthorDetails geTMovieMovieIdReviews200ResponseResultsInnerAuthorDetails = (GETMovieMovieIdReviews200ResponseResultsInnerAuthorDetails) o;
    return Objects.equals(this.name, geTMovieMovieIdReviews200ResponseResultsInnerAuthorDetails.name) &&
        Objects.equals(this.username, geTMovieMovieIdReviews200ResponseResultsInnerAuthorDetails.username) &&
        Objects.equals(this.avatarPath, geTMovieMovieIdReviews200ResponseResultsInnerAuthorDetails.avatarPath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, username, avatarPath);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETMovieMovieIdReviews200ResponseResultsInnerAuthorDetails {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    avatarPath: ").append(toIndentedString(avatarPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

