/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GETMovieMovieId200ResponseProductionCountriesInner
 */
@JsonPropertyOrder({
  GETMovieMovieId200ResponseProductionCountriesInner.JSON_PROPERTY_ISO31661,
  GETMovieMovieId200ResponseProductionCountriesInner.JSON_PROPERTY_NAME
})
@JsonTypeName("GET_movie_movie_id_200_response_production_countries_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T11:26:21.377642+02:00[Europe/Paris]")
public class GETMovieMovieId200ResponseProductionCountriesInner {
  public static final String JSON_PROPERTY_ISO31661 = "iso_3166_1";
  private String iso31661;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public GETMovieMovieId200ResponseProductionCountriesInner() {
  }

  public GETMovieMovieId200ResponseProductionCountriesInner iso31661(String iso31661) {
    
    this.iso31661 = iso31661;
    return this;
  }

   /**
   * Get iso31661
   * @return iso31661
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISO31661)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIso31661() {
    return iso31661;
  }


  @JsonProperty(JSON_PROPERTY_ISO31661)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIso31661(String iso31661) {
    this.iso31661 = iso31661;
  }


  public GETMovieMovieId200ResponseProductionCountriesInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETMovieMovieId200ResponseProductionCountriesInner geTMovieMovieId200ResponseProductionCountriesInner = (GETMovieMovieId200ResponseProductionCountriesInner) o;
    return Objects.equals(this.iso31661, geTMovieMovieId200ResponseProductionCountriesInner.iso31661) &&
        Objects.equals(this.name, geTMovieMovieId200ResponseProductionCountriesInner.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iso31661, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETMovieMovieId200ResponseProductionCountriesInner {\n");
    sb.append("    iso31661: ").append(toIndentedString(iso31661)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

