/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.GETPersonPersonIdChanges200ResponseChangesInnerItemsInnerOriginalValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GETPersonPersonIdChanges200ResponseChangesInnerItemsInner
 */
@JsonPropertyOrder({
  GETPersonPersonIdChanges200ResponseChangesInnerItemsInner.JSON_PROPERTY_ID,
  GETPersonPersonIdChanges200ResponseChangesInnerItemsInner.JSON_PROPERTY_ACTION,
  GETPersonPersonIdChanges200ResponseChangesInnerItemsInner.JSON_PROPERTY_TIME,
  GETPersonPersonIdChanges200ResponseChangesInnerItemsInner.JSON_PROPERTY_ORIGINAL_VALUE
})
@JsonTypeName("GET_person_person_id_changes_200_response_changes_inner_items_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T11:26:21.377642+02:00[Europe/Paris]")
public class GETPersonPersonIdChanges200ResponseChangesInnerItemsInner {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_ACTION = "action";
  private String action;

  public static final String JSON_PROPERTY_TIME = "time";
  private String time;

  public static final String JSON_PROPERTY_ORIGINAL_VALUE = "original_value";
  private GETPersonPersonIdChanges200ResponseChangesInnerItemsInnerOriginalValue originalValue;

  public GETPersonPersonIdChanges200ResponseChangesInnerItemsInner() {
  }

  public GETPersonPersonIdChanges200ResponseChangesInnerItemsInner id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public GETPersonPersonIdChanges200ResponseChangesInnerItemsInner action(String action) {
    
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAction() {
    return action;
  }


  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAction(String action) {
    this.action = action;
  }


  public GETPersonPersonIdChanges200ResponseChangesInnerItemsInner time(String time) {
    
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTime() {
    return time;
  }


  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTime(String time) {
    this.time = time;
  }


  public GETPersonPersonIdChanges200ResponseChangesInnerItemsInner originalValue(GETPersonPersonIdChanges200ResponseChangesInnerItemsInnerOriginalValue originalValue) {
    
    this.originalValue = originalValue;
    return this;
  }

   /**
   * Get originalValue
   * @return originalValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORIGINAL_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETPersonPersonIdChanges200ResponseChangesInnerItemsInnerOriginalValue getOriginalValue() {
    return originalValue;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINAL_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOriginalValue(GETPersonPersonIdChanges200ResponseChangesInnerItemsInnerOriginalValue originalValue) {
    this.originalValue = originalValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETPersonPersonIdChanges200ResponseChangesInnerItemsInner geTPersonPersonIdChanges200ResponseChangesInnerItemsInner = (GETPersonPersonIdChanges200ResponseChangesInnerItemsInner) o;
    return Objects.equals(this.id, geTPersonPersonIdChanges200ResponseChangesInnerItemsInner.id) &&
        Objects.equals(this.action, geTPersonPersonIdChanges200ResponseChangesInnerItemsInner.action) &&
        Objects.equals(this.time, geTPersonPersonIdChanges200ResponseChangesInnerItemsInner.time) &&
        Objects.equals(this.originalValue, geTPersonPersonIdChanges200ResponseChangesInnerItemsInner.originalValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, action, time, originalValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETPersonPersonIdChanges200ResponseChangesInnerItemsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    originalValue: ").append(toIndentedString(originalValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

