/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInnerValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner
 */
@JsonPropertyOrder({
  GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner.JSON_PROPERTY_ID,
  GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner.JSON_PROPERTY_ACTION,
  GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner.JSON_PROPERTY_TIME,
  GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner.JSON_PROPERTY_VALUE,
  GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner.JSON_PROPERTY_ISO6391,
  GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner.JSON_PROPERTY_ORIGINAL_VALUE
})
@JsonTypeName("GET_tv_season_season_id_changes_200_response_changes_inner_items_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T11:26:21.377642+02:00[Europe/Paris]")
public class GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_ACTION = "action";
  private String action;

  public static final String JSON_PROPERTY_TIME = "time";
  private String time;

  public static final String JSON_PROPERTY_VALUE = "value";
  private GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInnerValue value;

  public static final String JSON_PROPERTY_ISO6391 = "iso_639_1";
  private String iso6391;

  public static final String JSON_PROPERTY_ORIGINAL_VALUE = "original_value";
  private String originalValue;

  public GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner() {
  }

  public GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner action(String action) {
    
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAction() {
    return action;
  }


  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAction(String action) {
    this.action = action;
  }


  public GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner time(String time) {
    
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTime() {
    return time;
  }


  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTime(String time) {
    this.time = time;
  }


  public GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner value(GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInnerValue value) {
    
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInnerValue getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInnerValue value) {
    this.value = value;
  }


  public GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner iso6391(String iso6391) {
    
    this.iso6391 = iso6391;
    return this;
  }

   /**
   * Get iso6391
   * @return iso6391
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISO6391)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIso6391() {
    return iso6391;
  }


  @JsonProperty(JSON_PROPERTY_ISO6391)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIso6391(String iso6391) {
    this.iso6391 = iso6391;
  }


  public GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner originalValue(String originalValue) {
    
    this.originalValue = originalValue;
    return this;
  }

   /**
   * Get originalValue
   * @return originalValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORIGINAL_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOriginalValue() {
    return originalValue;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINAL_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOriginalValue(String originalValue) {
    this.originalValue = originalValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner geTTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner = (GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner) o;
    return Objects.equals(this.id, geTTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner.id) &&
        Objects.equals(this.action, geTTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner.action) &&
        Objects.equals(this.time, geTTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner.time) &&
        Objects.equals(this.value, geTTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner.value) &&
        Objects.equals(this.iso6391, geTTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner.iso6391) &&
        Objects.equals(this.originalValue, geTTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner.originalValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, action, time, value, iso6391, originalValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETTvSeasonSeasonIdChanges200ResponseChangesInnerItemsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    iso6391: ").append(toIndentedString(iso6391)).append("\n");
    sb.append("    originalValue: ").append(toIndentedString(originalValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

