/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.GETTvTvIdWatchProviders200ResponseResultsAR;
import org.openapitools.client.model.GETTvTvIdWatchProviders200ResponseResultsAT;
import org.openapitools.client.model.GETTvTvIdWatchProviders200ResponseResultsCA;
import org.openapitools.client.model.GETTvTvIdWatchProviders200ResponseResultsIT;
import org.openapitools.client.model.GETTvTvIdWatchProviders200ResponseResultsJP;
import org.openapitools.client.model.GETTvTvIdWatchProviders200ResponseResultsPL;
import org.openapitools.client.model.GETTvTvIdWatchProviders200ResponseResultsRU;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GETTvTvIdWatchProviders200ResponseResults
 */
@JsonPropertyOrder({
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_A_R,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_A_T,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_A_U,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_B_E,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_B_R,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_C_A,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_C_H,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_C_L,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_C_O,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_C_Z,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_D_E,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_D_K,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_E_C,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_E_S,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_F_I,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_F_R,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_G_B,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_H_U,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_I_E,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_I_N,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_I_T,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_J_P,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_M_X,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_N_L,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_N_O,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_N_Z,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_P_E,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_P_L,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_P_T,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_R_O,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_R_U,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_S_E,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_T_R,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_U_S,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_V_E,
  GETTvTvIdWatchProviders200ResponseResults.JSON_PROPERTY_Z_A
})
@JsonTypeName("GET_tv_tv_id_watch_providers_200_response_results")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T11:26:21.377642+02:00[Europe/Paris]")
public class GETTvTvIdWatchProviders200ResponseResults {
  public static final String JSON_PROPERTY_A_R = "AR";
  private GETTvTvIdWatchProviders200ResponseResultsAR AR;

  public static final String JSON_PROPERTY_A_T = "AT";
  private GETTvTvIdWatchProviders200ResponseResultsAT AT;

  public static final String JSON_PROPERTY_A_U = "AU";
  private GETTvTvIdWatchProviders200ResponseResultsAT AU;

  public static final String JSON_PROPERTY_B_E = "BE";
  private GETTvTvIdWatchProviders200ResponseResultsAR BE;

  public static final String JSON_PROPERTY_B_R = "BR";
  private GETTvTvIdWatchProviders200ResponseResultsAR BR;

  public static final String JSON_PROPERTY_C_A = "CA";
  private GETTvTvIdWatchProviders200ResponseResultsCA CA;

  public static final String JSON_PROPERTY_C_H = "CH";
  private GETTvTvIdWatchProviders200ResponseResultsCA CH;

  public static final String JSON_PROPERTY_C_L = "CL";
  private GETTvTvIdWatchProviders200ResponseResultsAR CL;

  public static final String JSON_PROPERTY_C_O = "CO";
  private GETTvTvIdWatchProviders200ResponseResultsAR CO;

  public static final String JSON_PROPERTY_C_Z = "CZ";
  private GETTvTvIdWatchProviders200ResponseResultsAR CZ;

  public static final String JSON_PROPERTY_D_E = "DE";
  private GETTvTvIdWatchProviders200ResponseResultsAT DE;

  public static final String JSON_PROPERTY_D_K = "DK";
  private GETTvTvIdWatchProviders200ResponseResultsAT DK;

  public static final String JSON_PROPERTY_E_C = "EC";
  private GETTvTvIdWatchProviders200ResponseResultsAR EC;

  public static final String JSON_PROPERTY_E_S = "ES";
  private GETTvTvIdWatchProviders200ResponseResultsAR ES;

  public static final String JSON_PROPERTY_F_I = "FI";
  private GETTvTvIdWatchProviders200ResponseResultsAT FI;

  public static final String JSON_PROPERTY_F_R = "FR";
  private GETTvTvIdWatchProviders200ResponseResultsCA FR;

  public static final String JSON_PROPERTY_G_B = "GB";
  private GETTvTvIdWatchProviders200ResponseResultsCA GB;

  public static final String JSON_PROPERTY_H_U = "HU";
  private GETTvTvIdWatchProviders200ResponseResultsAR HU;

  public static final String JSON_PROPERTY_I_E = "IE";
  private GETTvTvIdWatchProviders200ResponseResultsAT IE;

  public static final String JSON_PROPERTY_I_N = "IN";
  private GETTvTvIdWatchProviders200ResponseResultsAR IN;

  public static final String JSON_PROPERTY_I_T = "IT";
  private GETTvTvIdWatchProviders200ResponseResultsIT IT;

  public static final String JSON_PROPERTY_J_P = "JP";
  private GETTvTvIdWatchProviders200ResponseResultsJP JP;

  public static final String JSON_PROPERTY_M_X = "MX";
  private GETTvTvIdWatchProviders200ResponseResultsCA MX;

  public static final String JSON_PROPERTY_N_L = "NL";
  private GETTvTvIdWatchProviders200ResponseResultsAR NL;

  public static final String JSON_PROPERTY_N_O = "NO";
  private GETTvTvIdWatchProviders200ResponseResultsAT NO;

  public static final String JSON_PROPERTY_N_Z = "NZ";
  private GETTvTvIdWatchProviders200ResponseResultsAR NZ;

  public static final String JSON_PROPERTY_P_E = "PE";
  private GETTvTvIdWatchProviders200ResponseResultsAR PE;

  public static final String JSON_PROPERTY_P_L = "PL";
  private GETTvTvIdWatchProviders200ResponseResultsPL PL;

  public static final String JSON_PROPERTY_P_T = "PT";
  private GETTvTvIdWatchProviders200ResponseResultsAR PT;

  public static final String JSON_PROPERTY_R_O = "RO";
  private GETTvTvIdWatchProviders200ResponseResultsAR RO;

  public static final String JSON_PROPERTY_R_U = "RU";
  private GETTvTvIdWatchProviders200ResponseResultsRU RU;

  public static final String JSON_PROPERTY_S_E = "SE";
  private GETTvTvIdWatchProviders200ResponseResultsAT SE;

  public static final String JSON_PROPERTY_T_R = "TR";
  private GETTvTvIdWatchProviders200ResponseResultsAR TR;

  public static final String JSON_PROPERTY_U_S = "US";
  private GETTvTvIdWatchProviders200ResponseResultsAT US;

  public static final String JSON_PROPERTY_V_E = "VE";
  private GETTvTvIdWatchProviders200ResponseResultsAR VE;

  public static final String JSON_PROPERTY_Z_A = "ZA";
  private GETTvTvIdWatchProviders200ResponseResultsAR ZA;

  public GETTvTvIdWatchProviders200ResponseResults() {
  }

  public GETTvTvIdWatchProviders200ResponseResults AR(GETTvTvIdWatchProviders200ResponseResultsAR AR) {
    
    this.AR = AR;
    return this;
  }

   /**
   * Get AR
   * @return AR
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_R)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getAR() {
    return AR;
  }


  @JsonProperty(JSON_PROPERTY_A_R)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAR(GETTvTvIdWatchProviders200ResponseResultsAR AR) {
    this.AR = AR;
  }


  public GETTvTvIdWatchProviders200ResponseResults AT(GETTvTvIdWatchProviders200ResponseResultsAT AT) {
    
    this.AT = AT;
    return this;
  }

   /**
   * Get AT
   * @return AT
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_T)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAT getAT() {
    return AT;
  }


  @JsonProperty(JSON_PROPERTY_A_T)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAT(GETTvTvIdWatchProviders200ResponseResultsAT AT) {
    this.AT = AT;
  }


  public GETTvTvIdWatchProviders200ResponseResults AU(GETTvTvIdWatchProviders200ResponseResultsAT AU) {
    
    this.AU = AU;
    return this;
  }

   /**
   * Get AU
   * @return AU
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_A_U)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAT getAU() {
    return AU;
  }


  @JsonProperty(JSON_PROPERTY_A_U)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAU(GETTvTvIdWatchProviders200ResponseResultsAT AU) {
    this.AU = AU;
  }


  public GETTvTvIdWatchProviders200ResponseResults BE(GETTvTvIdWatchProviders200ResponseResultsAR BE) {
    
    this.BE = BE;
    return this;
  }

   /**
   * Get BE
   * @return BE
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getBE() {
    return BE;
  }


  @JsonProperty(JSON_PROPERTY_B_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBE(GETTvTvIdWatchProviders200ResponseResultsAR BE) {
    this.BE = BE;
  }


  public GETTvTvIdWatchProviders200ResponseResults BR(GETTvTvIdWatchProviders200ResponseResultsAR BR) {
    
    this.BR = BR;
    return this;
  }

   /**
   * Get BR
   * @return BR
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_B_R)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getBR() {
    return BR;
  }


  @JsonProperty(JSON_PROPERTY_B_R)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBR(GETTvTvIdWatchProviders200ResponseResultsAR BR) {
    this.BR = BR;
  }


  public GETTvTvIdWatchProviders200ResponseResults CA(GETTvTvIdWatchProviders200ResponseResultsCA CA) {
    
    this.CA = CA;
    return this;
  }

   /**
   * Get CA
   * @return CA
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_C_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsCA getCA() {
    return CA;
  }


  @JsonProperty(JSON_PROPERTY_C_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCA(GETTvTvIdWatchProviders200ResponseResultsCA CA) {
    this.CA = CA;
  }


  public GETTvTvIdWatchProviders200ResponseResults CH(GETTvTvIdWatchProviders200ResponseResultsCA CH) {
    
    this.CH = CH;
    return this;
  }

   /**
   * Get CH
   * @return CH
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_C_H)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsCA getCH() {
    return CH;
  }


  @JsonProperty(JSON_PROPERTY_C_H)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCH(GETTvTvIdWatchProviders200ResponseResultsCA CH) {
    this.CH = CH;
  }


  public GETTvTvIdWatchProviders200ResponseResults CL(GETTvTvIdWatchProviders200ResponseResultsAR CL) {
    
    this.CL = CL;
    return this;
  }

   /**
   * Get CL
   * @return CL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_C_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getCL() {
    return CL;
  }


  @JsonProperty(JSON_PROPERTY_C_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCL(GETTvTvIdWatchProviders200ResponseResultsAR CL) {
    this.CL = CL;
  }


  public GETTvTvIdWatchProviders200ResponseResults CO(GETTvTvIdWatchProviders200ResponseResultsAR CO) {
    
    this.CO = CO;
    return this;
  }

   /**
   * Get CO
   * @return CO
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_C_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getCO() {
    return CO;
  }


  @JsonProperty(JSON_PROPERTY_C_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCO(GETTvTvIdWatchProviders200ResponseResultsAR CO) {
    this.CO = CO;
  }


  public GETTvTvIdWatchProviders200ResponseResults CZ(GETTvTvIdWatchProviders200ResponseResultsAR CZ) {
    
    this.CZ = CZ;
    return this;
  }

   /**
   * Get CZ
   * @return CZ
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_C_Z)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getCZ() {
    return CZ;
  }


  @JsonProperty(JSON_PROPERTY_C_Z)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCZ(GETTvTvIdWatchProviders200ResponseResultsAR CZ) {
    this.CZ = CZ;
  }


  public GETTvTvIdWatchProviders200ResponseResults DE(GETTvTvIdWatchProviders200ResponseResultsAT DE) {
    
    this.DE = DE;
    return this;
  }

   /**
   * Get DE
   * @return DE
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_D_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAT getDE() {
    return DE;
  }


  @JsonProperty(JSON_PROPERTY_D_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDE(GETTvTvIdWatchProviders200ResponseResultsAT DE) {
    this.DE = DE;
  }


  public GETTvTvIdWatchProviders200ResponseResults DK(GETTvTvIdWatchProviders200ResponseResultsAT DK) {
    
    this.DK = DK;
    return this;
  }

   /**
   * Get DK
   * @return DK
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_D_K)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAT getDK() {
    return DK;
  }


  @JsonProperty(JSON_PROPERTY_D_K)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDK(GETTvTvIdWatchProviders200ResponseResultsAT DK) {
    this.DK = DK;
  }


  public GETTvTvIdWatchProviders200ResponseResults EC(GETTvTvIdWatchProviders200ResponseResultsAR EC) {
    
    this.EC = EC;
    return this;
  }

   /**
   * Get EC
   * @return EC
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_E_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getEC() {
    return EC;
  }


  @JsonProperty(JSON_PROPERTY_E_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEC(GETTvTvIdWatchProviders200ResponseResultsAR EC) {
    this.EC = EC;
  }


  public GETTvTvIdWatchProviders200ResponseResults ES(GETTvTvIdWatchProviders200ResponseResultsAR ES) {
    
    this.ES = ES;
    return this;
  }

   /**
   * Get ES
   * @return ES
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_E_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getES() {
    return ES;
  }


  @JsonProperty(JSON_PROPERTY_E_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setES(GETTvTvIdWatchProviders200ResponseResultsAR ES) {
    this.ES = ES;
  }


  public GETTvTvIdWatchProviders200ResponseResults FI(GETTvTvIdWatchProviders200ResponseResultsAT FI) {
    
    this.FI = FI;
    return this;
  }

   /**
   * Get FI
   * @return FI
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_F_I)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAT getFI() {
    return FI;
  }


  @JsonProperty(JSON_PROPERTY_F_I)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFI(GETTvTvIdWatchProviders200ResponseResultsAT FI) {
    this.FI = FI;
  }


  public GETTvTvIdWatchProviders200ResponseResults FR(GETTvTvIdWatchProviders200ResponseResultsCA FR) {
    
    this.FR = FR;
    return this;
  }

   /**
   * Get FR
   * @return FR
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_F_R)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsCA getFR() {
    return FR;
  }


  @JsonProperty(JSON_PROPERTY_F_R)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFR(GETTvTvIdWatchProviders200ResponseResultsCA FR) {
    this.FR = FR;
  }


  public GETTvTvIdWatchProviders200ResponseResults GB(GETTvTvIdWatchProviders200ResponseResultsCA GB) {
    
    this.GB = GB;
    return this;
  }

   /**
   * Get GB
   * @return GB
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_G_B)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsCA getGB() {
    return GB;
  }


  @JsonProperty(JSON_PROPERTY_G_B)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGB(GETTvTvIdWatchProviders200ResponseResultsCA GB) {
    this.GB = GB;
  }


  public GETTvTvIdWatchProviders200ResponseResults HU(GETTvTvIdWatchProviders200ResponseResultsAR HU) {
    
    this.HU = HU;
    return this;
  }

   /**
   * Get HU
   * @return HU
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_H_U)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getHU() {
    return HU;
  }


  @JsonProperty(JSON_PROPERTY_H_U)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHU(GETTvTvIdWatchProviders200ResponseResultsAR HU) {
    this.HU = HU;
  }


  public GETTvTvIdWatchProviders200ResponseResults IE(GETTvTvIdWatchProviders200ResponseResultsAT IE) {
    
    this.IE = IE;
    return this;
  }

   /**
   * Get IE
   * @return IE
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_I_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAT getIE() {
    return IE;
  }


  @JsonProperty(JSON_PROPERTY_I_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIE(GETTvTvIdWatchProviders200ResponseResultsAT IE) {
    this.IE = IE;
  }


  public GETTvTvIdWatchProviders200ResponseResults IN(GETTvTvIdWatchProviders200ResponseResultsAR IN) {
    
    this.IN = IN;
    return this;
  }

   /**
   * Get IN
   * @return IN
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_I_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getIN() {
    return IN;
  }


  @JsonProperty(JSON_PROPERTY_I_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIN(GETTvTvIdWatchProviders200ResponseResultsAR IN) {
    this.IN = IN;
  }


  public GETTvTvIdWatchProviders200ResponseResults IT(GETTvTvIdWatchProviders200ResponseResultsIT IT) {
    
    this.IT = IT;
    return this;
  }

   /**
   * Get IT
   * @return IT
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_I_T)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsIT getIT() {
    return IT;
  }


  @JsonProperty(JSON_PROPERTY_I_T)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIT(GETTvTvIdWatchProviders200ResponseResultsIT IT) {
    this.IT = IT;
  }


  public GETTvTvIdWatchProviders200ResponseResults JP(GETTvTvIdWatchProviders200ResponseResultsJP JP) {
    
    this.JP = JP;
    return this;
  }

   /**
   * Get JP
   * @return JP
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_J_P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsJP getJP() {
    return JP;
  }


  @JsonProperty(JSON_PROPERTY_J_P)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJP(GETTvTvIdWatchProviders200ResponseResultsJP JP) {
    this.JP = JP;
  }


  public GETTvTvIdWatchProviders200ResponseResults MX(GETTvTvIdWatchProviders200ResponseResultsCA MX) {
    
    this.MX = MX;
    return this;
  }

   /**
   * Get MX
   * @return MX
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_M_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsCA getMX() {
    return MX;
  }


  @JsonProperty(JSON_PROPERTY_M_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMX(GETTvTvIdWatchProviders200ResponseResultsCA MX) {
    this.MX = MX;
  }


  public GETTvTvIdWatchProviders200ResponseResults NL(GETTvTvIdWatchProviders200ResponseResultsAR NL) {
    
    this.NL = NL;
    return this;
  }

   /**
   * Get NL
   * @return NL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_N_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getNL() {
    return NL;
  }


  @JsonProperty(JSON_PROPERTY_N_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNL(GETTvTvIdWatchProviders200ResponseResultsAR NL) {
    this.NL = NL;
  }


  public GETTvTvIdWatchProviders200ResponseResults NO(GETTvTvIdWatchProviders200ResponseResultsAT NO) {
    
    this.NO = NO;
    return this;
  }

   /**
   * Get NO
   * @return NO
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_N_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAT getNO() {
    return NO;
  }


  @JsonProperty(JSON_PROPERTY_N_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNO(GETTvTvIdWatchProviders200ResponseResultsAT NO) {
    this.NO = NO;
  }


  public GETTvTvIdWatchProviders200ResponseResults NZ(GETTvTvIdWatchProviders200ResponseResultsAR NZ) {
    
    this.NZ = NZ;
    return this;
  }

   /**
   * Get NZ
   * @return NZ
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_N_Z)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getNZ() {
    return NZ;
  }


  @JsonProperty(JSON_PROPERTY_N_Z)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNZ(GETTvTvIdWatchProviders200ResponseResultsAR NZ) {
    this.NZ = NZ;
  }


  public GETTvTvIdWatchProviders200ResponseResults PE(GETTvTvIdWatchProviders200ResponseResultsAR PE) {
    
    this.PE = PE;
    return this;
  }

   /**
   * Get PE
   * @return PE
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_P_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getPE() {
    return PE;
  }


  @JsonProperty(JSON_PROPERTY_P_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPE(GETTvTvIdWatchProviders200ResponseResultsAR PE) {
    this.PE = PE;
  }


  public GETTvTvIdWatchProviders200ResponseResults PL(GETTvTvIdWatchProviders200ResponseResultsPL PL) {
    
    this.PL = PL;
    return this;
  }

   /**
   * Get PL
   * @return PL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_P_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsPL getPL() {
    return PL;
  }


  @JsonProperty(JSON_PROPERTY_P_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPL(GETTvTvIdWatchProviders200ResponseResultsPL PL) {
    this.PL = PL;
  }


  public GETTvTvIdWatchProviders200ResponseResults PT(GETTvTvIdWatchProviders200ResponseResultsAR PT) {
    
    this.PT = PT;
    return this;
  }

   /**
   * Get PT
   * @return PT
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_P_T)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getPT() {
    return PT;
  }


  @JsonProperty(JSON_PROPERTY_P_T)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPT(GETTvTvIdWatchProviders200ResponseResultsAR PT) {
    this.PT = PT;
  }


  public GETTvTvIdWatchProviders200ResponseResults RO(GETTvTvIdWatchProviders200ResponseResultsAR RO) {
    
    this.RO = RO;
    return this;
  }

   /**
   * Get RO
   * @return RO
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_R_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getRO() {
    return RO;
  }


  @JsonProperty(JSON_PROPERTY_R_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRO(GETTvTvIdWatchProviders200ResponseResultsAR RO) {
    this.RO = RO;
  }


  public GETTvTvIdWatchProviders200ResponseResults RU(GETTvTvIdWatchProviders200ResponseResultsRU RU) {
    
    this.RU = RU;
    return this;
  }

   /**
   * Get RU
   * @return RU
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_R_U)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsRU getRU() {
    return RU;
  }


  @JsonProperty(JSON_PROPERTY_R_U)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRU(GETTvTvIdWatchProviders200ResponseResultsRU RU) {
    this.RU = RU;
  }


  public GETTvTvIdWatchProviders200ResponseResults SE(GETTvTvIdWatchProviders200ResponseResultsAT SE) {
    
    this.SE = SE;
    return this;
  }

   /**
   * Get SE
   * @return SE
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_S_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAT getSE() {
    return SE;
  }


  @JsonProperty(JSON_PROPERTY_S_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSE(GETTvTvIdWatchProviders200ResponseResultsAT SE) {
    this.SE = SE;
  }


  public GETTvTvIdWatchProviders200ResponseResults TR(GETTvTvIdWatchProviders200ResponseResultsAR TR) {
    
    this.TR = TR;
    return this;
  }

   /**
   * Get TR
   * @return TR
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_T_R)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getTR() {
    return TR;
  }


  @JsonProperty(JSON_PROPERTY_T_R)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTR(GETTvTvIdWatchProviders200ResponseResultsAR TR) {
    this.TR = TR;
  }


  public GETTvTvIdWatchProviders200ResponseResults US(GETTvTvIdWatchProviders200ResponseResultsAT US) {
    
    this.US = US;
    return this;
  }

   /**
   * Get US
   * @return US
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_U_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAT getUS() {
    return US;
  }


  @JsonProperty(JSON_PROPERTY_U_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUS(GETTvTvIdWatchProviders200ResponseResultsAT US) {
    this.US = US;
  }


  public GETTvTvIdWatchProviders200ResponseResults VE(GETTvTvIdWatchProviders200ResponseResultsAR VE) {
    
    this.VE = VE;
    return this;
  }

   /**
   * Get VE
   * @return VE
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_V_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getVE() {
    return VE;
  }


  @JsonProperty(JSON_PROPERTY_V_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVE(GETTvTvIdWatchProviders200ResponseResultsAR VE) {
    this.VE = VE;
  }


  public GETTvTvIdWatchProviders200ResponseResults ZA(GETTvTvIdWatchProviders200ResponseResultsAR ZA) {
    
    this.ZA = ZA;
    return this;
  }

   /**
   * Get ZA
   * @return ZA
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_Z_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdWatchProviders200ResponseResultsAR getZA() {
    return ZA;
  }


  @JsonProperty(JSON_PROPERTY_Z_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZA(GETTvTvIdWatchProviders200ResponseResultsAR ZA) {
    this.ZA = ZA;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETTvTvIdWatchProviders200ResponseResults geTTvTvIdWatchProviders200ResponseResults = (GETTvTvIdWatchProviders200ResponseResults) o;
    return Objects.equals(this.AR, geTTvTvIdWatchProviders200ResponseResults.AR) &&
        Objects.equals(this.AT, geTTvTvIdWatchProviders200ResponseResults.AT) &&
        Objects.equals(this.AU, geTTvTvIdWatchProviders200ResponseResults.AU) &&
        Objects.equals(this.BE, geTTvTvIdWatchProviders200ResponseResults.BE) &&
        Objects.equals(this.BR, geTTvTvIdWatchProviders200ResponseResults.BR) &&
        Objects.equals(this.CA, geTTvTvIdWatchProviders200ResponseResults.CA) &&
        Objects.equals(this.CH, geTTvTvIdWatchProviders200ResponseResults.CH) &&
        Objects.equals(this.CL, geTTvTvIdWatchProviders200ResponseResults.CL) &&
        Objects.equals(this.CO, geTTvTvIdWatchProviders200ResponseResults.CO) &&
        Objects.equals(this.CZ, geTTvTvIdWatchProviders200ResponseResults.CZ) &&
        Objects.equals(this.DE, geTTvTvIdWatchProviders200ResponseResults.DE) &&
        Objects.equals(this.DK, geTTvTvIdWatchProviders200ResponseResults.DK) &&
        Objects.equals(this.EC, geTTvTvIdWatchProviders200ResponseResults.EC) &&
        Objects.equals(this.ES, geTTvTvIdWatchProviders200ResponseResults.ES) &&
        Objects.equals(this.FI, geTTvTvIdWatchProviders200ResponseResults.FI) &&
        Objects.equals(this.FR, geTTvTvIdWatchProviders200ResponseResults.FR) &&
        Objects.equals(this.GB, geTTvTvIdWatchProviders200ResponseResults.GB) &&
        Objects.equals(this.HU, geTTvTvIdWatchProviders200ResponseResults.HU) &&
        Objects.equals(this.IE, geTTvTvIdWatchProviders200ResponseResults.IE) &&
        Objects.equals(this.IN, geTTvTvIdWatchProviders200ResponseResults.IN) &&
        Objects.equals(this.IT, geTTvTvIdWatchProviders200ResponseResults.IT) &&
        Objects.equals(this.JP, geTTvTvIdWatchProviders200ResponseResults.JP) &&
        Objects.equals(this.MX, geTTvTvIdWatchProviders200ResponseResults.MX) &&
        Objects.equals(this.NL, geTTvTvIdWatchProviders200ResponseResults.NL) &&
        Objects.equals(this.NO, geTTvTvIdWatchProviders200ResponseResults.NO) &&
        Objects.equals(this.NZ, geTTvTvIdWatchProviders200ResponseResults.NZ) &&
        Objects.equals(this.PE, geTTvTvIdWatchProviders200ResponseResults.PE) &&
        Objects.equals(this.PL, geTTvTvIdWatchProviders200ResponseResults.PL) &&
        Objects.equals(this.PT, geTTvTvIdWatchProviders200ResponseResults.PT) &&
        Objects.equals(this.RO, geTTvTvIdWatchProviders200ResponseResults.RO) &&
        Objects.equals(this.RU, geTTvTvIdWatchProviders200ResponseResults.RU) &&
        Objects.equals(this.SE, geTTvTvIdWatchProviders200ResponseResults.SE) &&
        Objects.equals(this.TR, geTTvTvIdWatchProviders200ResponseResults.TR) &&
        Objects.equals(this.US, geTTvTvIdWatchProviders200ResponseResults.US) &&
        Objects.equals(this.VE, geTTvTvIdWatchProviders200ResponseResults.VE) &&
        Objects.equals(this.ZA, geTTvTvIdWatchProviders200ResponseResults.ZA);
  }

  @Override
  public int hashCode() {
    return Objects.hash(AR, AT, AU, BE, BR, CA, CH, CL, CO, CZ, DE, DK, EC, ES, FI, FR, GB, HU, IE, IN, IT, JP, MX, NL, NO, NZ, PE, PL, PT, RO, RU, SE, TR, US, VE, ZA);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETTvTvIdWatchProviders200ResponseResults {\n");
    sb.append("    AR: ").append(toIndentedString(AR)).append("\n");
    sb.append("    AT: ").append(toIndentedString(AT)).append("\n");
    sb.append("    AU: ").append(toIndentedString(AU)).append("\n");
    sb.append("    BE: ").append(toIndentedString(BE)).append("\n");
    sb.append("    BR: ").append(toIndentedString(BR)).append("\n");
    sb.append("    CA: ").append(toIndentedString(CA)).append("\n");
    sb.append("    CH: ").append(toIndentedString(CH)).append("\n");
    sb.append("    CL: ").append(toIndentedString(CL)).append("\n");
    sb.append("    CO: ").append(toIndentedString(CO)).append("\n");
    sb.append("    CZ: ").append(toIndentedString(CZ)).append("\n");
    sb.append("    DE: ").append(toIndentedString(DE)).append("\n");
    sb.append("    DK: ").append(toIndentedString(DK)).append("\n");
    sb.append("    EC: ").append(toIndentedString(EC)).append("\n");
    sb.append("    ES: ").append(toIndentedString(ES)).append("\n");
    sb.append("    FI: ").append(toIndentedString(FI)).append("\n");
    sb.append("    FR: ").append(toIndentedString(FR)).append("\n");
    sb.append("    GB: ").append(toIndentedString(GB)).append("\n");
    sb.append("    HU: ").append(toIndentedString(HU)).append("\n");
    sb.append("    IE: ").append(toIndentedString(IE)).append("\n");
    sb.append("    IN: ").append(toIndentedString(IN)).append("\n");
    sb.append("    IT: ").append(toIndentedString(IT)).append("\n");
    sb.append("    JP: ").append(toIndentedString(JP)).append("\n");
    sb.append("    MX: ").append(toIndentedString(MX)).append("\n");
    sb.append("    NL: ").append(toIndentedString(NL)).append("\n");
    sb.append("    NO: ").append(toIndentedString(NO)).append("\n");
    sb.append("    NZ: ").append(toIndentedString(NZ)).append("\n");
    sb.append("    PE: ").append(toIndentedString(PE)).append("\n");
    sb.append("    PL: ").append(toIndentedString(PL)).append("\n");
    sb.append("    PT: ").append(toIndentedString(PT)).append("\n");
    sb.append("    RO: ").append(toIndentedString(RO)).append("\n");
    sb.append("    RU: ").append(toIndentedString(RU)).append("\n");
    sb.append("    SE: ").append(toIndentedString(SE)).append("\n");
    sb.append("    TR: ").append(toIndentedString(TR)).append("\n");
    sb.append("    US: ").append(toIndentedString(US)).append("\n");
    sb.append("    VE: ").append(toIndentedString(VE)).append("\n");
    sb.append("    ZA: ").append(toIndentedString(ZA)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

