/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner
 */
@JsonPropertyOrder({
  GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner.JSON_PROPERTY_ID,
  GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner.JSON_PROPERTY_NAME,
  GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner.JSON_PROPERTY_CREDIT_ID,
  GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner.JSON_PROPERTY_CHARACTER,
  GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner.JSON_PROPERTY_ORDER,
  GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner.JSON_PROPERTY_PROFILE_PATH
})
@JsonTypeName("GET_tv_tv_id_season_season_number_episode_episode_number_200_response_guest_stars_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T11:26:21.377642+02:00[Europe/Paris]")
public class GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_CREDIT_ID = "credit_id";
  private String creditId;

  public static final String JSON_PROPERTY_CHARACTER = "character";
  private String character;

  public static final String JSON_PROPERTY_ORDER = "order";
  private Integer order;

  public static final String JSON_PROPERTY_PROFILE_PATH = "profile_path";
  private Object profilePath;

  public GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner() {
  }

  public GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner creditId(String creditId) {
    
    this.creditId = creditId;
    return this;
  }

   /**
   * Get creditId
   * @return creditId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREDIT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreditId() {
    return creditId;
  }


  @JsonProperty(JSON_PROPERTY_CREDIT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreditId(String creditId) {
    this.creditId = creditId;
  }


  public GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner character(String character) {
    
    this.character = character;
    return this;
  }

   /**
   * Get character
   * @return character
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHARACTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCharacter() {
    return character;
  }


  @JsonProperty(JSON_PROPERTY_CHARACTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCharacter(String character) {
    this.character = character;
  }


  public GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner order(Integer order) {
    
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOrder() {
    return order;
  }


  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrder(Integer order) {
    this.order = order;
  }


  public GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner profilePath(Object profilePath) {
    
    this.profilePath = profilePath;
    return this;
  }

   /**
   * Get profilePath
   * @return profilePath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROFILE_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getProfilePath() {
    return profilePath;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfilePath(Object profilePath) {
    this.profilePath = profilePath;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner geTTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner = (GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner) o;
    return Objects.equals(this.id, geTTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner.id) &&
        Objects.equals(this.name, geTTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner.name) &&
        Objects.equals(this.creditId, geTTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner.creditId) &&
        Objects.equals(this.character, geTTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner.character) &&
        Objects.equals(this.order, geTTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner.order) &&
        Objects.equals(this.profilePath, geTTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner.profilePath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, creditId, character, order, profilePath);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200ResponseGuestStarsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    creditId: ").append(toIndentedString(creditId)).append("\n");
    sb.append("    character: ").append(toIndentedString(character)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    profilePath: ").append(toIndentedString(profilePath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

