/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.GETTvTvIdEpisodeGroups200ResponseResultsInnerNetwork;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GETTvTvIdEpisodeGroups200ResponseResultsInner
 */
@JsonPropertyOrder({
  GETTvTvIdEpisodeGroups200ResponseResultsInner.JSON_PROPERTY_DESCRIPTION,
  GETTvTvIdEpisodeGroups200ResponseResultsInner.JSON_PROPERTY_EPISODE_COUNT,
  GETTvTvIdEpisodeGroups200ResponseResultsInner.JSON_PROPERTY_GROUP_COUNT,
  GETTvTvIdEpisodeGroups200ResponseResultsInner.JSON_PROPERTY_ID,
  GETTvTvIdEpisodeGroups200ResponseResultsInner.JSON_PROPERTY_NAME,
  GETTvTvIdEpisodeGroups200ResponseResultsInner.JSON_PROPERTY_NETWORK,
  GETTvTvIdEpisodeGroups200ResponseResultsInner.JSON_PROPERTY_TYPE
})
@JsonTypeName("GET_tv_tv_id_episode_groups_200_response_results_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T11:26:21.377642+02:00[Europe/Paris]")
public class GETTvTvIdEpisodeGroups200ResponseResultsInner {
  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_EPISODE_COUNT = "episode_count";
  private Integer episodeCount;

  public static final String JSON_PROPERTY_GROUP_COUNT = "group_count";
  private Integer groupCount;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_NETWORK = "network";
  private GETTvTvIdEpisodeGroups200ResponseResultsInnerNetwork network;

  public static final String JSON_PROPERTY_TYPE = "type";
  private Integer type;

  public GETTvTvIdEpisodeGroups200ResponseResultsInner() {
  }

  public GETTvTvIdEpisodeGroups200ResponseResultsInner description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public GETTvTvIdEpisodeGroups200ResponseResultsInner episodeCount(Integer episodeCount) {
    
    this.episodeCount = episodeCount;
    return this;
  }

   /**
   * Get episodeCount
   * @return episodeCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EPISODE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEpisodeCount() {
    return episodeCount;
  }


  @JsonProperty(JSON_PROPERTY_EPISODE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEpisodeCount(Integer episodeCount) {
    this.episodeCount = episodeCount;
  }


  public GETTvTvIdEpisodeGroups200ResponseResultsInner groupCount(Integer groupCount) {
    
    this.groupCount = groupCount;
    return this;
  }

   /**
   * Get groupCount
   * @return groupCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GROUP_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getGroupCount() {
    return groupCount;
  }


  @JsonProperty(JSON_PROPERTY_GROUP_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupCount(Integer groupCount) {
    this.groupCount = groupCount;
  }


  public GETTvTvIdEpisodeGroups200ResponseResultsInner id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public GETTvTvIdEpisodeGroups200ResponseResultsInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public GETTvTvIdEpisodeGroups200ResponseResultsInner network(GETTvTvIdEpisodeGroups200ResponseResultsInnerNetwork network) {
    
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdEpisodeGroups200ResponseResultsInnerNetwork getNetwork() {
    return network;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetwork(GETTvTvIdEpisodeGroups200ResponseResultsInnerNetwork network) {
    this.network = network;
  }


  public GETTvTvIdEpisodeGroups200ResponseResultsInner type(Integer type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(Integer type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETTvTvIdEpisodeGroups200ResponseResultsInner geTTvTvIdEpisodeGroups200ResponseResultsInner = (GETTvTvIdEpisodeGroups200ResponseResultsInner) o;
    return Objects.equals(this.description, geTTvTvIdEpisodeGroups200ResponseResultsInner.description) &&
        Objects.equals(this.episodeCount, geTTvTvIdEpisodeGroups200ResponseResultsInner.episodeCount) &&
        Objects.equals(this.groupCount, geTTvTvIdEpisodeGroups200ResponseResultsInner.groupCount) &&
        Objects.equals(this.id, geTTvTvIdEpisodeGroups200ResponseResultsInner.id) &&
        Objects.equals(this.name, geTTvTvIdEpisodeGroups200ResponseResultsInner.name) &&
        Objects.equals(this.network, geTTvTvIdEpisodeGroups200ResponseResultsInner.network) &&
        Objects.equals(this.type, geTTvTvIdEpisodeGroups200ResponseResultsInner.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, episodeCount, groupCount, id, name, network, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETTvTvIdEpisodeGroups200ResponseResultsInner {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    episodeCount: ").append(toIndentedString(episodeCount)).append("\n");
    sb.append("    groupCount: ").append(toIndentedString(groupCount)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

