/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.GETTvTvIdReviews200ResponseResultsInnerAuthorDetails;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GETTvTvIdReviews200ResponseResultsInner
 */
@JsonPropertyOrder({
  GETTvTvIdReviews200ResponseResultsInner.JSON_PROPERTY_AUTHOR,
  GETTvTvIdReviews200ResponseResultsInner.JSON_PROPERTY_AUTHOR_DETAILS,
  GETTvTvIdReviews200ResponseResultsInner.JSON_PROPERTY_CONTENT,
  GETTvTvIdReviews200ResponseResultsInner.JSON_PROPERTY_CREATED_AT,
  GETTvTvIdReviews200ResponseResultsInner.JSON_PROPERTY_ID,
  GETTvTvIdReviews200ResponseResultsInner.JSON_PROPERTY_UPDATED_AT,
  GETTvTvIdReviews200ResponseResultsInner.JSON_PROPERTY_URL
})
@JsonTypeName("GET_tv_tv_id_reviews_200_response_results_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T11:26:21.377642+02:00[Europe/Paris]")
public class GETTvTvIdReviews200ResponseResultsInner {
  public static final String JSON_PROPERTY_AUTHOR = "author";
  private String author;

  public static final String JSON_PROPERTY_AUTHOR_DETAILS = "author_details";
  private GETTvTvIdReviews200ResponseResultsInnerAuthorDetails authorDetails;

  public static final String JSON_PROPERTY_CONTENT = "content";
  private String content;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private String createdAt;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private String updatedAt;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public GETTvTvIdReviews200ResponseResultsInner() {
  }

  public GETTvTvIdReviews200ResponseResultsInner author(String author) {
    
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthor() {
    return author;
  }


  @JsonProperty(JSON_PROPERTY_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthor(String author) {
    this.author = author;
  }


  public GETTvTvIdReviews200ResponseResultsInner authorDetails(GETTvTvIdReviews200ResponseResultsInnerAuthorDetails authorDetails) {
    
    this.authorDetails = authorDetails;
    return this;
  }

   /**
   * Get authorDetails
   * @return authorDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUTHOR_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdReviews200ResponseResultsInnerAuthorDetails getAuthorDetails() {
    return authorDetails;
  }


  @JsonProperty(JSON_PROPERTY_AUTHOR_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthorDetails(GETTvTvIdReviews200ResponseResultsInnerAuthorDetails authorDetails) {
    this.authorDetails = authorDetails;
  }


  public GETTvTvIdReviews200ResponseResultsInner content(String content) {
    
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContent() {
    return content;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContent(String content) {
    this.content = content;
  }


  public GETTvTvIdReviews200ResponseResultsInner createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public GETTvTvIdReviews200ResponseResultsInner id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public GETTvTvIdReviews200ResponseResultsInner updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public GETTvTvIdReviews200ResponseResultsInner url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETTvTvIdReviews200ResponseResultsInner geTTvTvIdReviews200ResponseResultsInner = (GETTvTvIdReviews200ResponseResultsInner) o;
    return Objects.equals(this.author, geTTvTvIdReviews200ResponseResultsInner.author) &&
        Objects.equals(this.authorDetails, geTTvTvIdReviews200ResponseResultsInner.authorDetails) &&
        Objects.equals(this.content, geTTvTvIdReviews200ResponseResultsInner.content) &&
        Objects.equals(this.createdAt, geTTvTvIdReviews200ResponseResultsInner.createdAt) &&
        Objects.equals(this.id, geTTvTvIdReviews200ResponseResultsInner.id) &&
        Objects.equals(this.updatedAt, geTTvTvIdReviews200ResponseResultsInner.updatedAt) &&
        Objects.equals(this.url, geTTvTvIdReviews200ResponseResultsInner.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(author, authorDetails, content, createdAt, id, updatedAt, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETTvTvIdReviews200ResponseResultsInner {\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    authorDetails: ").append(toIndentedString(authorDetails)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

