/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GETTvTvIdWatchProviders200ResponseResultsARFlatrateInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GETTvTvIdWatchProviders200ResponseResultsCA
 */
@JsonPropertyOrder({
  GETTvTvIdWatchProviders200ResponseResultsCA.JSON_PROPERTY_LINK,
  GETTvTvIdWatchProviders200ResponseResultsCA.JSON_PROPERTY_FLATRATE,
  GETTvTvIdWatchProviders200ResponseResultsCA.JSON_PROPERTY_BUY
})
@JsonTypeName("GET_tv_tv_id_watch_providers_200_response_results_CA")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T11:26:21.377642+02:00[Europe/Paris]")
public class GETTvTvIdWatchProviders200ResponseResultsCA {
  public static final String JSON_PROPERTY_LINK = "link";
  private String link;

  public static final String JSON_PROPERTY_FLATRATE = "flatrate";
  private List<GETTvTvIdWatchProviders200ResponseResultsARFlatrateInner> flatrate = null;

  public static final String JSON_PROPERTY_BUY = "buy";
  private List<GETTvTvIdWatchProviders200ResponseResultsARFlatrateInner> buy = null;

  public GETTvTvIdWatchProviders200ResponseResultsCA() {
  }

  public GETTvTvIdWatchProviders200ResponseResultsCA link(String link) {
    
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLink(String link) {
    this.link = link;
  }


  public GETTvTvIdWatchProviders200ResponseResultsCA flatrate(List<GETTvTvIdWatchProviders200ResponseResultsARFlatrateInner> flatrate) {
    
    this.flatrate = flatrate;
    return this;
  }

  public GETTvTvIdWatchProviders200ResponseResultsCA addFlatrateItem(GETTvTvIdWatchProviders200ResponseResultsARFlatrateInner flatrateItem) {
    if (this.flatrate == null) {
      this.flatrate = new ArrayList<>();
    }
    this.flatrate.add(flatrateItem);
    return this;
  }

   /**
   * Get flatrate
   * @return flatrate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FLATRATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GETTvTvIdWatchProviders200ResponseResultsARFlatrateInner> getFlatrate() {
    return flatrate;
  }


  @JsonProperty(JSON_PROPERTY_FLATRATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlatrate(List<GETTvTvIdWatchProviders200ResponseResultsARFlatrateInner> flatrate) {
    this.flatrate = flatrate;
  }


  public GETTvTvIdWatchProviders200ResponseResultsCA buy(List<GETTvTvIdWatchProviders200ResponseResultsARFlatrateInner> buy) {
    
    this.buy = buy;
    return this;
  }

  public GETTvTvIdWatchProviders200ResponseResultsCA addBuyItem(GETTvTvIdWatchProviders200ResponseResultsARFlatrateInner buyItem) {
    if (this.buy == null) {
      this.buy = new ArrayList<>();
    }
    this.buy.add(buyItem);
    return this;
  }

   /**
   * Get buy
   * @return buy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BUY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GETTvTvIdWatchProviders200ResponseResultsARFlatrateInner> getBuy() {
    return buy;
  }


  @JsonProperty(JSON_PROPERTY_BUY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuy(List<GETTvTvIdWatchProviders200ResponseResultsARFlatrateInner> buy) {
    this.buy = buy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETTvTvIdWatchProviders200ResponseResultsCA geTTvTvIdWatchProviders200ResponseResultsCA = (GETTvTvIdWatchProviders200ResponseResultsCA) o;
    return Objects.equals(this.link, geTTvTvIdWatchProviders200ResponseResultsCA.link) &&
        Objects.equals(this.flatrate, geTTvTvIdWatchProviders200ResponseResultsCA.flatrate) &&
        Objects.equals(this.buy, geTTvTvIdWatchProviders200ResponseResultsCA.buy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(link, flatrate, buy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETTvTvIdWatchProviders200ResponseResultsCA {\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    flatrate: ").append(toIndentedString(flatrate)).append("\n");
    sb.append("    buy: ").append(toIndentedString(buy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

