/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.GETTvTvIdTranslations200ResponseTranslationsInnerData;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GETTvTvIdTranslations200ResponseTranslationsInner
 */
@JsonPropertyOrder({
  GETTvTvIdTranslations200ResponseTranslationsInner.JSON_PROPERTY_ISO31661,
  GETTvTvIdTranslations200ResponseTranslationsInner.JSON_PROPERTY_ISO6391,
  GETTvTvIdTranslations200ResponseTranslationsInner.JSON_PROPERTY_NAME,
  GETTvTvIdTranslations200ResponseTranslationsInner.JSON_PROPERTY_ENGLISH_NAME,
  GETTvTvIdTranslations200ResponseTranslationsInner.JSON_PROPERTY_DATA
})
@JsonTypeName("GET_tv_tv_id_translations_200_response_translations_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T11:26:21.377642+02:00[Europe/Paris]")
public class GETTvTvIdTranslations200ResponseTranslationsInner {
  public static final String JSON_PROPERTY_ISO31661 = "iso_3166_1";
  private String iso31661;

  public static final String JSON_PROPERTY_ISO6391 = "iso_639_1";
  private String iso6391;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_ENGLISH_NAME = "english_name";
  private String englishName;

  public static final String JSON_PROPERTY_DATA = "data";
  private GETTvTvIdTranslations200ResponseTranslationsInnerData data;

  public GETTvTvIdTranslations200ResponseTranslationsInner() {
  }

  public GETTvTvIdTranslations200ResponseTranslationsInner iso31661(String iso31661) {
    
    this.iso31661 = iso31661;
    return this;
  }

   /**
   * Get iso31661
   * @return iso31661
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISO31661)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIso31661() {
    return iso31661;
  }


  @JsonProperty(JSON_PROPERTY_ISO31661)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIso31661(String iso31661) {
    this.iso31661 = iso31661;
  }


  public GETTvTvIdTranslations200ResponseTranslationsInner iso6391(String iso6391) {
    
    this.iso6391 = iso6391;
    return this;
  }

   /**
   * Get iso6391
   * @return iso6391
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISO6391)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIso6391() {
    return iso6391;
  }


  @JsonProperty(JSON_PROPERTY_ISO6391)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIso6391(String iso6391) {
    this.iso6391 = iso6391;
  }


  public GETTvTvIdTranslations200ResponseTranslationsInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public GETTvTvIdTranslations200ResponseTranslationsInner englishName(String englishName) {
    
    this.englishName = englishName;
    return this;
  }

   /**
   * Get englishName
   * @return englishName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ENGLISH_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEnglishName() {
    return englishName;
  }


  @JsonProperty(JSON_PROPERTY_ENGLISH_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnglishName(String englishName) {
    this.englishName = englishName;
  }


  public GETTvTvIdTranslations200ResponseTranslationsInner data(GETTvTvIdTranslations200ResponseTranslationsInnerData data) {
    
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GETTvTvIdTranslations200ResponseTranslationsInnerData getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(GETTvTvIdTranslations200ResponseTranslationsInnerData data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETTvTvIdTranslations200ResponseTranslationsInner geTTvTvIdTranslations200ResponseTranslationsInner = (GETTvTvIdTranslations200ResponseTranslationsInner) o;
    return Objects.equals(this.iso31661, geTTvTvIdTranslations200ResponseTranslationsInner.iso31661) &&
        Objects.equals(this.iso6391, geTTvTvIdTranslations200ResponseTranslationsInner.iso6391) &&
        Objects.equals(this.name, geTTvTvIdTranslations200ResponseTranslationsInner.name) &&
        Objects.equals(this.englishName, geTTvTvIdTranslations200ResponseTranslationsInner.englishName) &&
        Objects.equals(this.data, geTTvTvIdTranslations200ResponseTranslationsInner.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iso31661, iso6391, name, englishName, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETTvTvIdTranslations200ResponseTranslationsInner {\n");
    sb.append("    iso31661: ").append(toIndentedString(iso31661)).append("\n");
    sb.append("    iso6391: ").append(toIndentedString(iso6391)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    englishName: ").append(toIndentedString(englishName)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

