/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner
 */
@JsonPropertyOrder({
  GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner.JSON_PROPERTY_ASPECT_RATIO,
  GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner.JSON_PROPERTY_FILE_PATH,
  GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner.JSON_PROPERTY_HEIGHT,
  GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner.JSON_PROPERTY_VOTE_COUNT,
  GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner.JSON_PROPERTY_WIDTH
})
@JsonTypeName("GET_tv_tv_id_season_season_number_episode_episode_number_images_200_response_stills_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T11:26:21.377642+02:00[Europe/Paris]")
public class GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner {
  public static final String JSON_PROPERTY_ASPECT_RATIO = "aspect_ratio";
  private BigDecimal aspectRatio;

  public static final String JSON_PROPERTY_FILE_PATH = "file_path";
  private String filePath;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  private Integer height;

  public static final String JSON_PROPERTY_VOTE_COUNT = "vote_count";
  private Integer voteCount;

  public static final String JSON_PROPERTY_WIDTH = "width";
  private Integer width;

  public GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner() {
  }

  public GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner aspectRatio(BigDecimal aspectRatio) {
    
    this.aspectRatio = aspectRatio;
    return this;
  }

   /**
   * Get aspectRatio
   * @return aspectRatio
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ASPECT_RATIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getAspectRatio() {
    return aspectRatio;
  }


  @JsonProperty(JSON_PROPERTY_ASPECT_RATIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAspectRatio(BigDecimal aspectRatio) {
    this.aspectRatio = aspectRatio;
  }


  public GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner filePath(String filePath) {
    
    this.filePath = filePath;
    return this;
  }

   /**
   * Get filePath
   * @return filePath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FILE_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilePath() {
    return filePath;
  }


  @JsonProperty(JSON_PROPERTY_FILE_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilePath(String filePath) {
    this.filePath = filePath;
  }


  public GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner height(Integer height) {
    
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHeight() {
    return height;
  }


  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeight(Integer height) {
    this.height = height;
  }


  public GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner voteCount(Integer voteCount) {
    
    this.voteCount = voteCount;
    return this;
  }

   /**
   * Get voteCount
   * @return voteCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VOTE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVoteCount() {
    return voteCount;
  }


  @JsonProperty(JSON_PROPERTY_VOTE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVoteCount(Integer voteCount) {
    this.voteCount = voteCount;
  }


  public GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner width(Integer width) {
    
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWidth() {
    return width;
  }


  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWidth(Integer width) {
    this.width = width;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner geTTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner = (GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner) o;
    return Objects.equals(this.aspectRatio, geTTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner.aspectRatio) &&
        Objects.equals(this.filePath, geTTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner.filePath) &&
        Objects.equals(this.height, geTTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner.height) &&
        Objects.equals(this.voteCount, geTTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner.voteCount) &&
        Objects.equals(this.width, geTTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner.width);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aspectRatio, filePath, height, voteCount, width);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberImages200ResponseStillsInner {\n");
    sb.append("    aspectRatio: ").append(toIndentedString(aspectRatio)).append("\n");
    sb.append("    filePath: ").append(toIndentedString(filePath)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    voteCount: ").append(toIndentedString(voteCount)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

